language: scala

dist: trusty

sudo: false

scala:
- 2.12.13
- 2.13.6

jdk:
- oraclejdk8

cache:
  directories:
    - '$HOME/.ivy2/cache'

# Test/compile covers the compilation of all the following sub-projects and their tests: examples and skuber
script:
  - sbt 'Test/compile;It/compile'